<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implement Hook_form_alter().
 */

function common_form_alter(&$form, FormStateInterface &$form_state, $form_id)
{
  if ($form_id == 'system_site_information_settings')
  {
    $site_api_key =  \Drupal::config('common.settings')->get('siteapikey');
    $form['siteapikey'] = array(
      '#type' => 'textfield',
      '#title' => 'Site Api Key',
      '#default_value' => ($site_api_key != '') ? $site_api_key: 'No API Key yet',
    );
    $form['actions']['submit']['#value'] = 'Update Configuration';
    $form['actions']['submit']['#submit'][]  = 'common_submit';
  }
}

function common_submit(&$form, FormStateInterface &$form_state)
{
  $site_api_key =   $form_state->getValue('siteapikey');
  \Drupal::configFactory()->getEditable('common.settings')->set('siteapikey', $site_api_key)->save();
  drupal_set_message(t('Site API Key has been saved with value: @value', array('@value'=>$site_api_key)), 'status');
}
